--TODO: 
-- create sample stations for escambia and bayou texar
-- populate/create point geom from lat/lons 
-- make sure it is in 4326
--See https://postgis.net/docs/ST_MakePoint.html for how to make a geom point from a lat/lon